### ISSUE TITLE
Lack of validation of RiskManager parameters

### ISSUE THREAD

**Issue by ggrieco-tob** [keep-network/coverage-pools#131]
```
Severity: Medium					Difficulty: High
Type: Data Validation			
Target: RiskManager.sol
```

**Description**
The RiskManager contract allows to change some important parameters without validation.

Deploying the RiskManager contract requires to provide a list of parameters, including the `bondAuctionThreshold` and `auctionLength` one:

https://github.com/keep-network/coverage-pools/blob/main/contracts/RiskManagerV1.sol#L182-L196

These parameters can be changed later, for instance:

https://github.com/keep-network/coverage-pools/blob/main/contracts/RiskManagerV1.sol#L305-L317

https://github.com/keep-network/coverage-pools/blob/main/contracts/RiskManagerV1.sol#L205-L226

However, these parameters are never validated and accept any numeric value.

**Exploit Scenario**

Alice deploys the risk manager contract, but some of the parameters are invalid (e.g. `auctionLength` is 0). Bob notifies new liquidations, creating an auction. When some user tries to interact with that auction, they are unable to do it because the invalid `auctionLength` causes a zero division revert when calling `onTake`.

**Recommendation** 

Short term, properly validate the `bondAuctionThreshold` and `auctionLength` values, in particular if they are zero or very large values that can trigger an overflow.

Long term, review all the function inputs to make sure they are properly validated. Use Echidna and Manticore to test them.

**Comment by pdyraga** [comment]
This is controversial but... we decided to not implement the validation for any of them as it is hard to say what the correct range is, and to make it clear that it is up to the calling party (governance) to make sure values make sense.

For example, 0 `auctionLength` does not really make sense, but same for 1,2,...,100,... - it all depends on the TVL, same for the upper bound. For `bondAuctionThreshold` we could probably limit it to <= 100 but given that we do not validate other parameters, we did not add it here for consistency so that we do not suggest the rest of the parameters will be fine with arbitrary values.

I would lean towards going through all governable parameters and making it clear in the Solidity docs what are the expectations about the values accepted.
