### ISSUE TITLE
Lack of chainID validation allows re-using signatures across forks

### ISSUE THREAD

**Issue by montyly** [keep-network/coverage-pools#61]
Severity: High
Difficulty: High

## Description
Calling `UnderwriterToken.permit` allows an asset holder to move tokens on behalf of another user by using a signature. The lack of `chainId` verification on every signature can enable an attacker to withdraw rewards multiple times if the chain is forked.

`UnderwriterToken.permit` uses `ecrecover` to allow changing the approval of users:
https://github.com/keep-network/coverage-pools/blob/4aee098edbd4755d57dcfc7649ca80ab105500bb/contracts/ERC20WithPermit.sol#L101-L146

A domain separator and the chainID are included in the signature scheme when the contract is deployed:
https://github.com/keep-network/coverage-pools/blob/4aee098edbd4755d57dcfc7649ca80ab105500bb/contracts/ERC20WithPermit.sol#L48-L61

However, this `chainID` is read at the time of deployment. In the event of a post-deployment chain hard fork, the `chainID` cannot be updated, and signatures may be replayed across both versions of the chain. As a result, an attacker could reuse signatures to receive user funds on both chains. 

## Exploit Scenario
A fork of mainnet is performed on Eth 2.0. The tokens on the old chain lose their value, but they keep the same value on the new chain. Bob allows Eve to transfer its tokens on the old chain. Eve uses the signature to also withdraw the tokens on the new chain. 

## Recommendations
Short term, add `chainID` to the signature schema to prevent post-deployment forks from affecting this permit.

Long term, identify and document the risks associated with having forks of multiple chains, and develop related mitigation strategies.

**Comment by pdyraga** [comment]
I am afraid I am not entirely following and I need some more explanation. Is this issue only about Ethereum 1.0 -> Ethereum 2.0 upgrade or about Ethereum 1.0 chain forks as well?

Once ready, Ethereum 1.0 will merge with Ethereum 2.0 Beacon Chain, becoming its own shard so the state of the contract will be maintained.  Eve can not replay permit transactions because Ethereum 2.0 will expect a higher nonce in the Permit structure.

Thinking about two different chains with two different IDs, Eve can not replay permit transactions because of a different chain ID in DOMAIN_SEPARATOR.

In the case of forks at the same chain, say Ethereum 1.0 chain forks, transactions can be replayed between forks but that is always true, not only in case of `ERC20WithPermit`.

**Comment by montyly** [comment]
I used eth 1 > eth 2 as an example, but the exploit works with any fork on eth 1 that is done after the deployment of `UnderwriterToken`.

Put in another words, after the fork, `DOMAIN_SEPARATOR` will be the same in both forks, because it is evaluated at deployment only. 

> In the case of forks at the same chain, say Ethereum 1.0 chain forks, transactions can be replayed between forks but that is always true, not only in case of ERC20WithPermit, and thus allows replays.

`chainId` was introduced to prevent this (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md); the encoding of the transaction contains now the `chainID` and prevent the replay.

**Comment by pdyraga** [comment]
For this issue to happen, eth 1 fork needs to have another chain ID, correct? I think the best way to address it could be to validate the current chain ID against the cached one and if they do not match, build a new domain separator and use it in `permit`.
