### ISSUE TITLE
Standarize Solidity version used

### ISSUE THREAD

**Issue by pdyraga** [keep-network/coverage-pools#98]
Some of the contracts use 0.8, some others 0.7. We need to standardize the Solidity version referenced, probably to 0.7.

**Comment by ggrieco-tob** [comment]
Related with this, I believe the pragma used by several contracts (`pragma solidity <0.9.0;`) is too broad and can induce security or correctness issues. Since such pragma allows 0.7.x and 0.8.x, the developers can overlook certain features if they have to downgrade the compiler versions.

**Exploit scenario**

If a contract is compiled using 0.8.x, solc will include mandatory integer overflow checks. As expected, contract developers are tempted to remove the use of SafeMath, since it is redundant and waste gas. However, if the optimized contract is later compiled with solc 0.7.x, the integer overflow checks will be silently removed.

**Recommendation**

Select either 0.7.x or 0.8.x solc versions to compile contracts and include a suitable pragma for it.

**Comment by pdyraga** [comment]
Confirmed with Trail of Bits: 

> In terms of solc versions, 0.8.x is fine, as long it's not the latest release (which sometimes contains latent issues). Right now, latest release is 0.8.5, so 0.8.4 is fine, in particular since the fixed a high-severity issue related with the decoder.

I recommend we stick to 0.8.4, and review the contracts so they use 0.8.x features, especially review all `SafeMath` usages.
